version: '2.1'
services:
    redis:
        image: 'redis:3.2.7'
        # command: redis-server --requirepass redispass

    postgres:
        image: postgres:9.6
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow

    webserver:
        image: puckel/docker-airflow:1.10.0-2
        restart: always
        depends_on:
            - postgres
            - redis
        environment:
            - LOAD_EX=n
            - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
            - EXECUTOR=Celery
            - PYTHONPATH=${LIB_DEST}
        volumes:
            - ${DAGS_PATH}:${DAGS_DEST}
            - ${LIB_PATH}:${LIB_DEST}
        ports:
            - "8080:8080"
        command: webserver
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3

    flower:
        image: puckel/docker-airflow:1.10.0-2
        restart: always
        depends_on:
            - redis
        environment:
            - EXECUTOR=Celery
            # - REDIS_PASSWORD=redispass
        ports:
            - "5555:5555"
        command: flower

    scheduler:
        image: puckel/docker-airflow:1.10.0-2
        restart: always
        depends_on:
            - webserver
        volumes:
            - ${DAGS_PATH}:${DAGS_DEST}
            - ${LIB_PATH}:${LIB_DEST}
        environment:
            - LOAD_EX=n
            - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
            - EXECUTOR=Celery
            - PYTHONPATH=${LIB_DEST}
        command: scheduler

    worker:
        image: puckel/docker-airflow:1.10.0-2
        restart: always
        depends_on:
            - scheduler
        volumes:
            - ${DAGS_PATH}:${DAGS_DEST}
            - ${LIB_PATH}:${LIB_DEST}
        environment:
            - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
            - EXECUTOR=Celery
            - PYTHONPATH=${LIB_DEST}
        command: worker
